# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171017_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pass',
            field=models.CharField(max_length=64),
        ),
    ]
