# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_amout',
            new_name='cart_amount',
        ),
    ]
