# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_advertise_category_goodsinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertise',
        ),
        migrations.RemoveField(
            model_name='goodsinfo',
            name='goods_cag',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='GoodsInfo',
        ),
    ]
